In [1]:
# numpy

In [2]:
import numpy as np

In [3]:
# vector

In [4]:
x = np.array([1,2,3])

In [5]:
y = np.array([2.,3.9,6.1])

In [6]:
x

array([1, 2, 3])

In [7]:
y

array([2. , 3.9, 6.1])

In [8]:
x.mean()

2.0

In [9]:
y.mean()

4.0

In [10]:
# 中心化

In [11]:
xc = x - x.mean()

In [15]:
xc

array([-1.,  0.,  1.])

In [13]:
y = y - y.mean()

In [14]:
y

array([-2. , -0.1,  2.1])

In [16]:
# parameter a

In [17]:
# 要素積

In [18]:
x*x

array([1, 4, 9])

In [19]:
xc*xc

array([1., 0., 1.])

In [20]:
xx=xc*xc

In [21]:
xc*yc

NameError: name 'yc' is not defined

In [22]:
a = xy.sum()

NameError: name 'xy' is not defined